### ISSUE TITLE
Make A-c etc buffer local mappings

### ISSUE THREAD

**Issue by madskjeldgaard** [salkin-mada/openscad.nvim#3]
There are two global mappings in the plugin which can be a bit confusing: 
https://github.com/salkin-mada/openscad.nvim/blob/7651583af081b9a55375f9ad2932134ee774bd3d/lua/openscad.lua#L127-L128

can we make them buffer local like the others? would be dope!

**Comment by salkin-mada** [comment]
Yes of course. PR's are welcome.
